pipeline{
  agent {
    label 'prod'
  }

  tools {
    maven 'mymaven'
  }

  stages{
    stage('build'){
      steps{
        echo "this is build stage "
      }
    }
    stage('test'){
      steps{
        echo "this is test stage "
      }
    }
  }
}
